name: solution_challenge_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  transparent_image: ^2.0.1
  url_launcher: ^6.2.2
  flutter_riverpod: ^2.4.9
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  image_picker: ^1.0.7
  cloud_firestore: ^4.14.0
  firebase_messaging: ^14.7.10
  uuid: ^4.3.3
  firebase_database: ^10.4.0
  location: ^5.0.3
  flutter_map: ^6.1.0
  latlng: ^1.0.0
  latlong2: ^0.9.0
  google_polyline_algorithm: ^3.1.0
  smooth_page_indicator: ^1.1.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0

  flutter_barcode_scanner: ^2.0.0
  pretty_qr_code: ^3.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1
  




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/chat.png
    - assets/images/trash.avif
    - assets/images/origin.jpg
    - assets/images/0.png
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/analyse.jpg
    - assets/images/click_1.jpg
    - assets/images/click_2.webp
    - assets/images/collect.avif
    - assets/images/jogging.png
    - assets/images/logo.png
    - assets/images/repeat.jpg
    - assets/images/rewards.avif
    - assets/images/share.avif
    - assets/images/trash.avif
    - assets/images/verify.jpg
    - assets/images/jogging-removebg-preview.png
    - assets/images/pick_up_garbage-removebg-preview.png
    - assets/images/click_2-1-removebg-preview.png
    - assets/images/analyse-removebg-preview.png
    - assets/images/verify-removebg-preview.png
    - assets/images/repeat-removebg-preview.png
    - assets/images/repeat-removebg-preview_1.png
    - assets/images/rewards-0-removebg-preview.png
    - assets/images/share-1-removebg-preview.png
    - assets/images/logo.png
    - assets/images/logo_1.png
    - assets/images/logo_2.jpg
    - assets/images/exit.jpg
    - assets/images/map.jpg
    - assets/images/success.jpg
    - assets/images/winner.jpg
    - assets/images/trophies.jpg
    - assets/images/first.png
    - assets/images/second.jpg
    - assets/images/third.jpg
    - assets/images/others.jpg
    - assets/images/pinpoint.png
    

   
    
    
   
    
   
    
    
    
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
